"""empty message

Revision ID: a9412e4aea07
Revises: 
Create Date: 2020-07-06 10:52:28.905061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9412e4aea07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('articleId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('articleId')
    )
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=True)
    op.create_table('categories',
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('categoryId')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('tagId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], ),
    sa.PrimaryKeyConstraint('tagId')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('articles_assoc_tags',
    sa.Column('tagId', sa.Integer(), nullable=True),
    sa.Column('articleId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articleId'], ['articles.articleId'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tags.tagId'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles_assoc_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
